package majava.enums;

public enum GameplayEvent {
	START_OF_ROUND,
	DREW_TILE,
	NEW_DORA_INDICATOR,
	DISCARDED_TILE, CALLED_TILE, MADE_OPEN_MELD,
	DECLARED_RIICHI, MADE_ANKAN, MADE_MINKAN, MADE_OWN_KAN,
	END_OF_ROUND,
	UNKNOWN, PLACEHOLDER;
}
